### ISSUE TITLE
'undefined' is not a package

### ISSUE THREAD

**Issue by RenhaoL** [cs107-undefined/cs107-FinalProject#10]
Thanks for making the tag! 

When I tried it on my machine in a new conda environment, import `undefined` will work, but it does not import the trace function? 

When I try `from undefined.API import trace`, I got the following error:
`>>> from undefined.API import trace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'undefined.API'; 'undefined' is not a package`

Maybe this will need a special way to interact with?

**Comment by XinranTang** [comment]
Please try downloading undefined-1.0.0.whl from the release page and use after: pip install the downloaded package.
