### ISSUE TITLE
derivative orders

### ISSUE THREAD

**Issue by RenhaoL** [cs107-undefined/cs107-FinalProject#12]
>>> f2 = lambda x, y: sin(x)+ exp(y) + 2*x
>>> print(trace(f2, x= 1, y = 2))
value: 10.23
derivative: [2.54  7.389]
>>> print(trace(f2, y = 2, x = 1))
value: 10.23
derivative: [7.389 2.54 ]
>>>

Change so that x always comes first.

**Comment by XinranTang** [comment]
Solved
``` python
>>> f2 = lambda x, y: sin(x)+ exp(y) + 2*x
>>> print(trace(f2, x= 1, y = 2))
(10.23, array([2.54 , 7.389]))
>>> print(trace(f2, y = 2, x = 1))
(10.23, array([2.54 , 7.389]))
```
