### ISSUE TITLE
graph automatically generated in the reverse mode.

### ISSUE THREAD

**Issue by RenhaoL** [cs107-undefined/cs107-FinalProject#21]
We probably should let the user to choose whether they want to display the graph or not. 
It will also make writing the test easier. Maybe we can add one more option in the trace(), say "display_graph = True", to show the graph. 
right now, I will have to manually close the graphs in order to test the outcomes.

**Comment by cswbuild** [comment]
Note: Cannot manually round result1 (cannot pass a tuple into round function)

**Comment by cswbuild** [comment]
Change plt.plot to plt.savefig() to prevent it from stopping the program/tests.
In addition, prompt user on whether or not to generate plot.

**Comment by XinranTang** [comment]
Solved
