### ISSUE TITLE
More test cases expected

### ISSUE THREAD

**Issue by XinranTang** [cs107-undefined/cs107-FinalProject#33]
Example expected test cases:

tests for all functions with one input: x = np.array([[1,2]]), x = 2,147,483,647, x = np.array([[99999, -99999, 0.0001]])
tests for all functions with two inputs: x = np.array([[1,2]]), y = np.array([[2,1]]); x = np.array([[-1,2]]), y = np.array([[-2,-1]]); x = np.array([[1,2]]), y = np.array([[2,1]]); x = 2, y = np.array([[2,1]])

Other example expected test cases:
Test cases for raising ValueError: such as x = -1 for log(), x = np.array([[-1,-100,1,2]]) for log(), x = 2 for arccos()

**Comment by RenhaoL** [comment]
resolved!
