### ISSUE TITLE
Tests on UDFunction

### ISSUE THREAD

**Issue by XinranTang** [cs107-undefined/cs107-FinalProject#6]
Tests for scalar functions on scalar/vector and vector functions on scalar/vector should be passed.

**Comment by RenhaoL** [comment]
The UDFunction cannot work with subtraction. For example: when the input function is 2*x - beta, error raised "TypeError: unsupported operand type(s) for -: 'UDFunction' and 'float'". Same thing happened to division when testing 3*x/2

Suggested solution: overwrite the __sub__, __rsub__, __div__, and __rdiv__.

**Comment by XinranTang** [comment]
> **sub**, **rsub**, **div**, and **rdiv**

Methods added in UDFunction. Please feel free to write any tests.
