### ISSUE TITLE
New tests required for UDFunction

### ISSUE THREAD

**Issue by XinranTang** [cs107-undefined/cs107-FinalProject#7]
The floor division, division, pow functions can be tested.

**Comment by RenhaoL** [comment]
I created some simple tests for mentioned functions, and those pass the Travis CI. There are a few cases that I did not cover in my testing, but I will add more tests later. 

Btw, the codecov and travis are working in milestone2 branch.

**Comment by XinranTang** [comment]
Thank you Renhao!
